name: jup
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  provider: ^6.1.5+1
  google_fonts: ^6.3.2
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#F4EDE4" # айвори
  adaptive_icon_foreground: "assets/icon/app_icon.png"

flutter_native_splash:
  color: "#F4EDE4"
  image: assets/icon/app_icon.png

  android_12:
    color: "#F4EDE4"
    image: assets/icon/app_icon.png

  ios: true
  android: true


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/